services:
  db:
    image: postgres:17.2
    container_name: postgres-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # express:
  #   image: node:22.14.0-alpine
  #   working_dir: /app
  #   command: /bin/sh -c "npm install && npm run dev"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   ports:
  #     - "${EXPRESS_PORT}:5000"
  #   environment:
  #     PORT: ${EXPRESS_PORT}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     PGHOST: ${POSTGRES_HOST}
  #   depends_on:
  #     - db


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  # frontend:
  #   image: node:18
  #   working_dir: /app
  #   command: /bin/sh -c "npm install && npm start"
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     REACT_APP_API_URL: http://localhost:5000
  #   depends_on:
  #     - express

volumes:
  db-data:
  pgadmin_data:
